package main

import (
	"flag"
	"fmt"
	"os"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/types/pluginpb"
)

var (
	useProtoNames   = flag.Bool("UseProtoNames", false, "uses proto field name instead of lowerCamelCase name in JSON field names")
	useEnumNumbers  = flag.Bool("UseEnumNumbers", false, "emits enum values as numbers.")
	emitUnpopulated = flag.Bool("EmitUnpopulated", false, `specifies whether to emit unpopulated fields. It does not emit unpopulated oneof fields or unpopulated extension fields.`)
	discardUnknown  = flag.Bool("DiscardUnknown", false, "unknown fields are ignored.")
)

func main() {
	flag.Parse()
	protogen.Options{
		ParamFunc: flag.CommandLine.Set,
	}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		for _, f := range plugin.Files {
			if !f.Generate {
				continue
			}
			if len(f.Messages) == 0 {
				continue
			}
			filename := f.GeneratedFilenamePrefix + ".pb.json.go"
			file := plugin.NewGeneratedFile(filename, f.GoImportPath)
			ApplyTemplate(file, f)
		}

		return nil
	})
}

func ApplyTemplate(file *protogen.GeneratedFile, f *protogen.File) {
	file.P(`// Code generated by protoc-gen-go-meta. DO NOT EDIT.`)
	file.P(`// github.com/yvvlee/protoc-gen-go-json `)
	file.P(`package ` + f.GoPackageName)
	file.P(`import (
	"google.golang.org/protobuf/encoding/protojson"
)`)
	applyMessages(file, f.Messages)
}

func applyMessages(file *protogen.GeneratedFile, msgs []*protogen.Message) {
	for _, m := range msgs {
		if m.Desc.IsMapEntry() {
			continue
		}
		if err := messageTemplate.Execute(file, tplMessage{
			Message: m,
			MarshalOptions: &protojson.MarshalOptions{
				UseProtoNames:   *useProtoNames,
				UseEnumNumbers:  *useEnumNumbers,
				EmitUnpopulated: *emitUnpopulated,
			},
			UnmarshalOptions: &protojson.UnmarshalOptions{
				DiscardUnknown: *discardUnknown,
			},
		}); err != nil {
			fmt.Fprintf(os.Stderr, "protoc-gen-go-json error: %v\n", err)
		}
		applyMessages(file, m.Messages)
	}
}
